'use client'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import Header from '../components/Header'
import { UserProvider } from '@/components/context/UserContext'
import { I18nextProvider } from 'react-i18next'
import i18n from '../../i18n'
import { useEffect } from 'react'
//  import { applyRTL } from './rtlUtils
// const geistSans = localFont({
//   src: './fonts/GeistVF.woff',
//   variable: '--font-geist-sans',
//   weight: '100 900'
// })
// const geistMono = localFont({
//   src: './fonts/GeistMonoVF.woff',
//   variable: '--font-geist-mono',
//   weight: '100 900'
// })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app'
// }

export default function RootLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <UserProvider>
      <I18nextProvider i18n={i18n}>
        <html lang='ar' dir='rtl'>
          <body>
            <Header />
            {children}
          </body>
        </html>
      </I18nextProvider>
    </UserProvider>
  )
}
